# Generated by Django 3.1.2 on 2020-11-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_posts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
