# Generated by Django 3.1.2 on 2020-11-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postedby',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
