# Generated by Django 3.1.2 on 2020-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201120_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
